<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EscortsMediasBannerTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('escorts_medias')->insert([
            [
                'type'      => 0,
                'banner_group'  => '1',
                'path'      => 'escorts/images/template/banner/bdsm/BDSM-Banner01.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '1',
                'path'      => 'escorts/images/template/banner/bdsm/BDSM-Banner01.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '1',
                'path'      => 'escorts/images/template/banner/bdsm/BDSM-Banner02.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '1',
                'path'      => 'escorts/images/template/banner/bdsm/BDSM-Banner03.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '1',
                'path'      => 'escorts/images/template/banner/bdsm/BDSM-Banner04.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '1',
                'path'      => 'escorts/images/template/banner/bdsm/BDSM-Banner05.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner01.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner02.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner03.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner04.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner05.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner06.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner07.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner08.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner09.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner10.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner11.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '2',
                'path'      => 'escorts/images/template/banner/lingerie/Lingerie-Banner12.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '3',
                'path'      => 'escorts/images/template/banner/passive/Passive-Banner01.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '3',
                'path'      => 'escorts/images/template/banner/passive/Passive-Banner02.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '3',
                'path'      => 'escorts/images/template/banner/passive/Passive-Banner03.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '3',
                'path'      => 'escorts/images/template/banner/passive/Passive-Banner04.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '3',
                'path'      => 'escorts/images/template/banner/passive/Passive-Banner05.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '4',
                'path'      => 'escorts/images/template/banner/sheets/Sheets-Banner01.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '4',
                'path'      => 'escorts/images/template/banner/sheets/Sheets-Banner02.jpg',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '4',
                'path'      => 'escorts/images/template/banner/sheets/Sheets-Banner03.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '4',
                'path'      => 'escorts/images/template/banner/sheets/Sheets-Banner04.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '4',
                'path'      => 'escorts/images/template/banner/sheets/Sheets-Banner05.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '5',
                'path'      => 'escorts/images/template/banner/subtle/Subtle-Banner01.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '5',
                'path'      => 'escorts/images/template/banner/subtle/Subtle-Banner02.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '5',
                'path'      => 'escorts/images/template/banner/subtle/Subtle-Banner03.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '5',
                'path'      => 'escorts/images/template/banner/subtle/Subtle-Banner04.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'type'      => 0,
                'banner_group'  => '5',
                'path'      => 'escorts/images/template/banner/subtle/Subtle-Banner05.png',
                'template'     => '1',
                'position' => 9,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],

        ]);
    }
}
