@extends('layouts.center')
@section('style')
    <style>
        #masseursStatisticsTable tbody tr td,
        #masseursStatisticsTable thead tr th {
            text-align: center;
        }

        #masseursStatisticsTable tbody tr td:nth-child(2) {
            text-align: left !important;
            margin-right: 20px;
    object-fit: cover;
        }
    </style>
@endsection
@section('content')
    <div class="container-fluid  pl-3 pl-lg-5 pr-3 pr-lg-5">
        <div class="d-sm-flex align-items-center justify-content-between">
            <div class="custom-heading-wrapper">
                <h1 class="h1">Masseur Statistics</h1>
                <span class="helpNoteLink" data-toggle="collapse" data-target="#notes" aria-expanded="true"><b>Help?</b></span>
            </div>
            @if (request('from') == 'dashboard')
                <div class="back-to-dashboard">
                    <a href="{{ url()->previous() ?? route('dashboard.home') }}">
                        <img src="{{ asset('assets/dashboard/img/crossimg.png') }}" alt="Back To Dashboard">
                    </a>
                </div>
            @endif
        </div>

        <div class="row">
            <div class="col-md-12 mb-4 collapse" id="notes">
                <div class="card " id="notes">
                    <div class="card-body">
                        <h3 class="NotesHeader"><b>Notes:</b> </h3>
                        <ol>
                            <li>The following statistics are a summary of the activity generated by Users who have
                                viewed your Masseurs on your Profile page.</li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="w-100 table table-bordered" id="masseursStatisticsTable" style="">
                        <thead class="table-bg">
                            <tr>
                                <th colspan="3"></th>
                                <th colspan="3" class="text-center">Profile Views</th>
                                <th colspan="3" class="text-center">Media Views</th>
                            </tr>
                            <tr>
                                <th>ID</th>
                                <th>Masseur</th>
                                <th>Status</th>
                                <th class="text-center">Today</th>
                                <th class="text-center">This Week</th>
                                <th class="text-center">Year to Date</th>
                                <th class="text-center">Today</th>
                                <th class="text-center">This Week</th>
                                <th class="text-center">Year to Date</th>
                            </tr>

                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
@endsection
@push('script')
    <!-- opr_accordian_table JS -->
    <script src="{{ asset('assets/dashboard/vendor/jquery/jquery.min.js') }}"></script>


    <script type="text/javascript" charset="utf8" src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}">
    </script>


    <script>
        var table = $("#masseursStatisticsTable").DataTable({
            processing: true,
            serverSide: true,

            ajax: "{{ route('masseurs.list') }}",

            language: {
                search: "Search: _INPUT_",
                searchPlaceholder: "Search by Name"
            },

            info: true,
            paging: true,
            lengthChange: true,
            searching: true,
            bStateSave: true,

            order: [
                [1, 'desc']
            ],

            lengthMenu: [
                [10, 25, 50, 100],
                [10, 25, 50, 100]
            ],

            pageLength: 10,

            columns: [{
                    data: 'member_id',
                    name: 'member_id',
                    searchable: false,
                    orderable: false,
                    defaultContent: 'NA'
                },
                {
                    data: 'masseur',
                    name: 'name',
                    searchable: true,
                    orderable: true,
                    defaultContent: 'NA'
                },
                {
                    data: 'status',
                    name: 'status',
                    searchable: true,
                    orderable: true,
                    defaultContent: 'NA'
                },
                {
                    data: 'profile_today',
                    name: 'profile_today',
                    searchable: false,
                    orderable: false,
                    defaultContent: '0'
                },
                {
                    data: 'profile_this_week',
                    name: 'profile_this_week',
                    searchable: false,
                    orderable: false,
                    defaultContent: '0'
                },
                {
                    data: 'profile_year_to_date',
                    name: 'profile_year_to_date',
                    searchable: false,
                    orderable: false,
                    defaultContent: '0'
                },
                {
                    data: 'media_today',
                    name: 'media_today',
                    searchable: false,
                    orderable: false,
                    defaultContent: '0'
                },
                {
                    data: 'media_this_week',
                    name: 'media_this_week',
                    searchable: false,
                    orderable: false,
                    defaultContent: '0'
                },
                {
                    data: 'media_year_to_date',
                    name: 'media_year_to_date',
                    searchable: false,
                    orderable: false,
                    defaultContent: '0'
                }
            ]
        });
    </script>
@endpush
