@extends('layouts.center')
@section('style')
@endsection
@section('content')
    <div class="container-fluid  pl-3 pl-lg-5 pr-3 pr-lg-5">
        <div class="row">

            <div class="col-lg-12">
                <div class="d-sm-flex align-items-center justify-content-between">
                    <div class="custom-heading-wrapper">
                        <h1 class="h1">Profiles</h1>
                        <span class="helpNoteLink" data-toggle="collapse" data-target="#notes" aria-expanded="true">
                            <b>Help?</b></span>
                    </div>
                    @if (request('from') == 'dashboard')
                        <div class="back-to-dashboard">
                            <a href="{{ url()->previous() ?? route('dashboard.home') }}">
                                <img src="{{ asset('assets/dashboard/img/crossimg.png') }}" alt="Back To Dashboard">
                            </a>
                        </div>
                    @endif
                </div>
            </div>
            <div class="col-md-12 mb-4">
                <div class="card collapse" id="notes">
                    <div class="card-body">
                        <h3 class="NotesHeader"><b>Notes:</b></h3>
                        <ol>
                            <li>The following statistics are a summary of the activity generated by Users who have viewed
                                your Profile pages.</li>
                            <li>View your statistics here for your Profile views</li>
                            <li>For Masseur statistics, go to <a href="{{ route('masseurs') }}"
                                    class="custom_links_design">Masseurs</a>.</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-12 common-card mb-3">
            <div class="card-top">
                <div class="card-icon">
                    <svg width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
                        fill="#000000">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <defs>
                                <style>
                                    .a,
                                    .b {
                                        fill: none;
                                        stroke: #ff3c5f;
                                        stroke-linecap: round;
                                        stroke-linejoin: round;
                                        stroke-width: 1.9440000000000002;
                                    }

                                    .a {
                                        fill-rule: evenodd;
                                    }
                                </style>
                            </defs>
                            <path class="a" d="M2,2V20a2,2,0,0,0,2,2H22"></path>
                            <rect class="b" height="6" rx="1.5" width="3" x="6" y="12"></rect>
                            <rect class="b" height="6" rx="1.5" width="3" x="12" y="7"></rect>
                            <rect class="b" height="6" rx="1.5" width="3" x="18" y="3"></rect>
                        </g>
                    </svg>
                </div>
                <div class="card-heading">
                    <h2>Profile Statistics</h2>
                </div>
            </div>
            <hr class="custom-hr">
            <div class="stats-card-grid">
                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path d="M22 12C22 6.49 17.51 2 12 2C6.49 2 2 6.49 2 12C2 14.9 3.25 17.51 5.23 19.34C5.23 19.35 5.23 19.35 5.22 19.36C5.32 19.46 5.44 19.54 5.54 19.63C5.6 19.68 5.65 19.73 5.71 19.77C5.89 19.92 6.09 20.06 6.28 20.2C6.35 20.25 6.41 20.29 6.48 20.34C6.67 20.47 6.87 20.59 7.08 20.7C7.15 20.74 7.23 20.79 7.3 20.83C7.5 20.94 7.71 21.04 7.93 21.13C8.01 21.17 8.09 21.21 8.17 21.24C8.39 21.33 8.61 21.41 8.83 21.48C8.91 21.51 8.99 21.54 9.07 21.56C9.31 21.63 9.55 21.69 9.79 21.75C9.86 21.77 9.93 21.79 10.01 21.8C10.29 21.86 10.57 21.9 10.86 21.93C10.9 21.93 10.94 21.94 10.98 21.95C11.32 21.98 11.66 22 12 22C12.34 22 12.68 21.98 13.01 21.95C13.05 21.95 13.09 21.94 13.13 21.93C13.42 21.9 13.7 21.86 13.98 21.8C14.05 21.79 14.12 21.76 14.2 21.75C14.44 21.69 14.69 21.64 14.92 21.56C15 21.53 15.08 21.5 15.16 21.48C15.38 21.4 15.61 21.33 15.82 21.24C15.9 21.21 15.98 21.17 16.06 21.13C16.27 21.04 16.48 20.94 16.69 20.83C16.77 20.79 16.84 20.74 16.91 20.7C17.11 20.58 17.31 20.47 17.51 20.34C17.58 20.3 17.64 20.25 17.71 20.2C17.91 20.06 18.1 19.92 18.28 19.77C18.34 19.72 18.39 19.67 18.45 19.63C18.56 19.54 18.67 19.45 18.77 19.36C18.77 19.35 18.77 19.35 18.76 19.34C20.75 17.51 22 14.9 22 12ZM16.94 16.97C14.23 15.15 9.79 15.15 7.06 16.97C6.62 17.26 6.26 17.6 5.96 17.97C4.44 16.43 3.5 14.32 3.5 12C3.5 7.31 7.31 3.5 12 3.5C16.69 3.5 20.5 7.31 20.5 12C20.5 14.32 19.56 16.43 18.04 17.97C17.75 17.6 17.38 17.26 16.94 16.97Z" fill="#ff3c5f"></path>
                                    <path d="M12 6.92969C9.93 6.92969 8.25 8.60969 8.25 10.6797C8.25 12.7097 9.84 14.3597 11.95 14.4197C11.98 14.4197 12.02 14.4197 12.04 14.4197C12.06 14.4197 12.09 14.4197 12.11 14.4197C12.12 14.4197 12.13 14.4197 12.13 14.4197C14.15 14.3497 15.74 12.7097 15.75 10.6797C15.75 8.60969 14.07 6.92969 12 6.92969Z" fill="#ff3c5f"></path>
                                </g>
                            </svg>
                        </div>
                        <div class="stat-text">
                            <div class="stats-label ">Profile Views Today</div>
                            <div class="stats-value">125</div>
                        </div>
                    </div>
                </div>

                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path d="M22 12C22 6.49 17.51 2 12 2C6.49 2 2 6.49 2 12C2 14.9 3.25 17.51 5.23 19.34C5.23 19.35 5.23 19.35 5.22 19.36C5.32 19.46 5.44 19.54 5.54 19.63C5.6 19.68 5.65 19.73 5.71 19.77C5.89 19.92 6.09 20.06 6.28 20.2C6.35 20.25 6.41 20.29 6.48 20.34C6.67 20.47 6.87 20.59 7.08 20.7C7.15 20.74 7.23 20.79 7.3 20.83C7.5 20.94 7.71 21.04 7.93 21.13C8.01 21.17 8.09 21.21 8.17 21.24C8.39 21.33 8.61 21.41 8.83 21.48C8.91 21.51 8.99 21.54 9.07 21.56C9.31 21.63 9.55 21.69 9.79 21.75C9.86 21.77 9.93 21.79 10.01 21.8C10.29 21.86 10.57 21.9 10.86 21.93C10.9 21.93 10.94 21.94 10.98 21.95C11.32 21.98 11.66 22 12 22C12.34 22 12.68 21.98 13.01 21.95C13.05 21.95 13.09 21.94 13.13 21.93C13.42 21.9 13.7 21.86 13.98 21.8C14.05 21.79 14.12 21.76 14.2 21.75C14.44 21.69 14.69 21.64 14.92 21.56C15 21.53 15.08 21.5 15.16 21.48C15.38 21.4 15.61 21.33 15.82 21.24C15.9 21.21 15.98 21.17 16.06 21.13C16.27 21.04 16.48 20.94 16.69 20.83C16.77 20.79 16.84 20.74 16.91 20.7C17.11 20.58 17.31 20.47 17.51 20.34C17.58 20.3 17.64 20.25 17.71 20.2C17.91 20.06 18.1 19.92 18.28 19.77C18.34 19.72 18.39 19.67 18.45 19.63C18.56 19.54 18.67 19.45 18.77 19.36C18.77 19.35 18.77 19.35 18.76 19.34C20.75 17.51 22 14.9 22 12ZM16.94 16.97C14.23 15.15 9.79 15.15 7.06 16.97C6.62 17.26 6.26 17.6 5.96 17.97C4.44 16.43 3.5 14.32 3.5 12C3.5 7.31 7.31 3.5 12 3.5C16.69 3.5 20.5 7.31 20.5 12C20.5 14.32 19.56 16.43 18.04 17.97C17.75 17.6 17.38 17.26 16.94 16.97Z" fill="#ff3c5f"></path>
                                    <path d="M12 6.92969C9.93 6.92969 8.25 8.60969 8.25 10.6797C8.25 12.7097 9.84 14.3597 11.95 14.4197C11.98 14.4197 12.02 14.4197 12.04 14.4197C12.06 14.4197 12.09 14.4197 12.11 14.4197C12.12 14.4197 12.13 14.4197 12.13 14.4197C14.15 14.3497 15.74 12.7097 15.75 10.6797C15.75 8.60969 14.07 6.92969 12 6.92969Z" fill="#ff3c5f"></path>
                                </g>
                            </svg>
                        </div>
                        <div class="stat-text">
                            <div class="stats-label">Profile Views This Week</div>
                            <div class="stats-value">35</div>
                        </div>
                    </div>
                </div>

                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path d="M22 12C22 6.49 17.51 2 12 2C6.49 2 2 6.49 2 12C2 14.9 3.25 17.51 5.23 19.34C5.23 19.35 5.23 19.35 5.22 19.36C5.32 19.46 5.44 19.54 5.54 19.63C5.6 19.68 5.65 19.73 5.71 19.77C5.89 19.92 6.09 20.06 6.28 20.2C6.35 20.25 6.41 20.29 6.48 20.34C6.67 20.47 6.87 20.59 7.08 20.7C7.15 20.74 7.23 20.79 7.3 20.83C7.5 20.94 7.71 21.04 7.93 21.13C8.01 21.17 8.09 21.21 8.17 21.24C8.39 21.33 8.61 21.41 8.83 21.48C8.91 21.51 8.99 21.54 9.07 21.56C9.31 21.63 9.55 21.69 9.79 21.75C9.86 21.77 9.93 21.79 10.01 21.8C10.29 21.86 10.57 21.9 10.86 21.93C10.9 21.93 10.94 21.94 10.98 21.95C11.32 21.98 11.66 22 12 22C12.34 22 12.68 21.98 13.01 21.95C13.05 21.95 13.09 21.94 13.13 21.93C13.42 21.9 13.7 21.86 13.98 21.8C14.05 21.79 14.12 21.76 14.2 21.75C14.44 21.69 14.69 21.64 14.92 21.56C15 21.53 15.08 21.5 15.16 21.48C15.38 21.4 15.61 21.33 15.82 21.24C15.9 21.21 15.98 21.17 16.06 21.13C16.27 21.04 16.48 20.94 16.69 20.83C16.77 20.79 16.84 20.74 16.91 20.7C17.11 20.58 17.31 20.47 17.51 20.34C17.58 20.3 17.64 20.25 17.71 20.2C17.91 20.06 18.1 19.92 18.28 19.77C18.34 19.72 18.39 19.67 18.45 19.63C18.56 19.54 18.67 19.45 18.77 19.36C18.77 19.35 18.77 19.35 18.76 19.34C20.75 17.51 22 14.9 22 12ZM16.94 16.97C14.23 15.15 9.79 15.15 7.06 16.97C6.62 17.26 6.26 17.6 5.96 17.97C4.44 16.43 3.5 14.32 3.5 12C3.5 7.31 7.31 3.5 12 3.5C16.69 3.5 20.5 7.31 20.5 12C20.5 14.32 19.56 16.43 18.04 17.97C17.75 17.6 17.38 17.26 16.94 16.97Z" fill="#ff3c5f"></path>
                                    <path d="M12 6.92969C9.93 6.92969 8.25 8.60969 8.25 10.6797C8.25 12.7097 9.84 14.3597 11.95 14.4197C11.98 14.4197 12.02 14.4197 12.04 14.4197C12.06 14.4197 12.09 14.4197 12.11 14.4197C12.12 14.4197 12.13 14.4197 12.13 14.4197C14.15 14.3497 15.74 12.7097 15.75 10.6797C15.75 8.60969 14.07 6.92969 12 6.92969Z" fill="#ff3c5f"></path>
                                </g>
                            </svg>
                        </div>
                        <div class="stat-text">
                            <div class="stats-label ">Year to Date</div>
                            <div class="stats-value">125</div>
                        </div>
                    </div>
                </div>

                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            <img src="{{ asset('assets/app/img/MyPlaybox.png') }}" alt="" class="w-100 p-2">
                        </div>
                        <div class="stat-text">
                            <div class="stats-label">Playbox Views Today</div>
                            <div class="stats-value">125</div>
                        </div>
                    </div>
                </div>

                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            
                            <img src="{{ asset('assets/app/img/MyPlaybox.png') }}" alt="" class="w-100 p-2">
                        </div>
                        <div class="stat-text">
                            <div class="stats-label">Playbox Views This Week</div>
                            <div class="stats-value">35</div>
                        </div>
                    </div>
                </div>

                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            
                            <img src="{{ asset('assets/app/img/MyPlaybox.png') }}" alt="" class="w-100 p-2">
                        </div>
                        <div class="stat-text">
                            <div class="stats-label">Year to Date</div>
                            <div class="stats-value">125</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12 common-card">
            <div class="card-top">
                <div class="card-icon">
                    <svg width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
                        fill="#000000">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <defs>
                                <style>
                                    .a,
                                    .b {
                                        fill: none;
                                        stroke: #ff3c5f;
                                        stroke-linecap: round;
                                        stroke-linejoin: round;
                                        stroke-width: 1.9440000000000002;
                                    }

                                    .a {
                                        fill-rule: evenodd;
                                    }
                                </style>
                            </defs>
                            <path class="a" d="M2,2V20a2,2,0,0,0,2,2H22"></path>
                            <rect class="b" height="6" rx="1.5" width="3" x="6" y="12"></rect>
                            <rect class="b" height="6" rx="1.5" width="3" x="12" y="7"></rect>
                            <rect class="b" height="6" rx="1.5" width="3" x="18" y="3"></rect>
                        </g>
                    </svg>
                </div>
                <div class="card-heading">
                    <h2>Media Statistics</h2>
                </div>
            </div>
            <hr class="custom-hr">
            <div class="stats-card-grid">
                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            <svg fill="#ff3c5f" height="24px" width="24px" version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" xml:space="preserve">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <g>
                                        <path d="M23,7H9c-1.7,0-3,1.3-3,3v10.7l9.5-5.5c0.3-0.2,0.8-0.2,1.1,0.1l3.5,2.6l5.9-3.6V10C26,8.3,24.7,7,23,7z M12,14 c-1.1,0-2-0.9-2-2s0.9-2,2-2s2,0.9,2,2S13.1,14,12,14z">
                                        </path>
                                        <path d="M19.4,19.8l-3.5-2.6l-9.8,5.7C6.5,24.1,7.7,25,9,25h14c1.7,0,3-1.3,3-3v-5.4l-5.5,3.3C20.2,20.1,19.7,20,19.4,19.8z">
                                        </path>
                                        <path d="M13.7,5.7L16,3.4l2.3,2.3C18.5,5.9,18.7,6,19,6s0.5-0.1,0.7-0.3c0.4-0.4,0.4-1,0-1.4l-3-3c-0.4-0.4-1-0.4-1.4,0l-3,3 c-0.4,0.4-0.4,1,0,1.4S13.3,6.1,13.7,5.7z">
                                        </path>
                                        <path d="M18.3,26.3L16,28.6l-2.3-2.3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4l3,3c0.2,0.2,0.5,0.3,0.7,0.3s0.5-0.1,0.7-0.3l3-3 c0.4-0.4,0.4-1,0-1.4S18.7,25.9,18.3,26.3z">
                                        </path>
                                        <path d="M4.7,12.3c-0.4-0.4-1-0.4-1.4,0l-3,3c-0.4,0.4-0.4,1,0,1.4l3,3C3.5,19.9,3.7,20,4,20s0.5-0.1,0.7-0.3c0.4-0.4,0.4-1,0-1.4 L2.4,16l2.3-2.3C5.1,13.3,5.1,12.7,4.7,12.3z">
                                        </path>
                                        <path d="M31.7,15.3l-3-3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4l2.3,2.3l-2.3,2.3c-0.4,0.4-0.4,1,0,1.4c0.2,0.2,0.5,0.3,0.7,0.3 s0.5-0.1,0.7-0.3l3-3C32.1,16.3,32.1,15.7,31.7,15.3z">
                                        </path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <div class="stat-text">
                            <div class="stats-label ">Media Views Today</div>
                            <div class="stats-value">125</div>
                        </div>
                    </div>
                </div>

                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            <svg fill="#ff3c5f" height="24px" width="24px" version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" xml:space="preserve">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <g>
                                        <path d="M23,7H9c-1.7,0-3,1.3-3,3v10.7l9.5-5.5c0.3-0.2,0.8-0.2,1.1,0.1l3.5,2.6l5.9-3.6V10C26,8.3,24.7,7,23,7z M12,14 c-1.1,0-2-0.9-2-2s0.9-2,2-2s2,0.9,2,2S13.1,14,12,14z">
                                        </path>
                                        <path d="M19.4,19.8l-3.5-2.6l-9.8,5.7C6.5,24.1,7.7,25,9,25h14c1.7,0,3-1.3,3-3v-5.4l-5.5,3.3C20.2,20.1,19.7,20,19.4,19.8z">
                                        </path>
                                        <path d="M13.7,5.7L16,3.4l2.3,2.3C18.5,5.9,18.7,6,19,6s0.5-0.1,0.7-0.3c0.4-0.4,0.4-1,0-1.4l-3-3c-0.4-0.4-1-0.4-1.4,0l-3,3 c-0.4,0.4-0.4,1,0,1.4S13.3,6.1,13.7,5.7z">
                                        </path>
                                        <path d="M18.3,26.3L16,28.6l-2.3-2.3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4l3,3c0.2,0.2,0.5,0.3,0.7,0.3s0.5-0.1,0.7-0.3l3-3 c0.4-0.4,0.4-1,0-1.4S18.7,25.9,18.3,26.3z">
                                        </path>
                                        <path d="M4.7,12.3c-0.4-0.4-1-0.4-1.4,0l-3,3c-0.4,0.4-0.4,1,0,1.4l3,3C3.5,19.9,3.7,20,4,20s0.5-0.1,0.7-0.3c0.4-0.4,0.4-1,0-1.4 L2.4,16l2.3-2.3C5.1,13.3,5.1,12.7,4.7,12.3z">
                                        </path>
                                        <path d="M31.7,15.3l-3-3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4l2.3,2.3l-2.3,2.3c-0.4,0.4-0.4,1,0,1.4c0.2,0.2,0.5,0.3,0.7,0.3 s0.5-0.1,0.7-0.3l3-3C32.1,16.3,32.1,15.7,31.7,15.3z">
                                        </path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <div class="stat-text">
                            <div class="stats-label">Media Views This Weeks</div>
                            <div class="stats-value">35</div>
                        </div>
                    </div>
                </div>

                <div class="stats-card">
                    <div class="stats-details">
                        <div class="stats-icon">
                            <svg fill="#ff3c5f" height="24px" width="24px" version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" xml:space="preserve">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <g>
                                        <path d="M23,7H9c-1.7,0-3,1.3-3,3v10.7l9.5-5.5c0.3-0.2,0.8-0.2,1.1,0.1l3.5,2.6l5.9-3.6V10C26,8.3,24.7,7,23,7z M12,14 c-1.1,0-2-0.9-2-2s0.9-2,2-2s2,0.9,2,2S13.1,14,12,14z">
                                        </path>
                                        <path d="M19.4,19.8l-3.5-2.6l-9.8,5.7C6.5,24.1,7.7,25,9,25h14c1.7,0,3-1.3,3-3v-5.4l-5.5,3.3C20.2,20.1,19.7,20,19.4,19.8z">
                                        </path>
                                        <path d="M13.7,5.7L16,3.4l2.3,2.3C18.5,5.9,18.7,6,19,6s0.5-0.1,0.7-0.3c0.4-0.4,0.4-1,0-1.4l-3-3c-0.4-0.4-1-0.4-1.4,0l-3,3 c-0.4,0.4-0.4,1,0,1.4S13.3,6.1,13.7,5.7z">
                                        </path>
                                        <path d="M18.3,26.3L16,28.6l-2.3-2.3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4l3,3c0.2,0.2,0.5,0.3,0.7,0.3s0.5-0.1,0.7-0.3l3-3 c0.4-0.4,0.4-1,0-1.4S18.7,25.9,18.3,26.3z">
                                        </path>
                                        <path d="M4.7,12.3c-0.4-0.4-1-0.4-1.4,0l-3,3c-0.4,0.4-0.4,1,0,1.4l3,3C3.5,19.9,3.7,20,4,20s0.5-0.1,0.7-0.3c0.4-0.4,0.4-1,0-1.4 L2.4,16l2.3-2.3C5.1,13.3,5.1,12.7,4.7,12.3z">
                                        </path>
                                        <path d="M31.7,15.3l-3-3c-0.4-0.4-1-0.4-1.4,0s-0.4,1,0,1.4l2.3,2.3l-2.3,2.3c-0.4,0.4-0.4,1,0,1.4c0.2,0.2,0.5,0.3,0.7,0.3 s0.5-0.1,0.7-0.3l3-3C32.1,16.3,32.1,15.7,31.7,15.3z">
                                        </path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <div class="stat-text">
                            <div class="stats-label ">Year to Date</div>
                            <div class="stats-value">125</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
@endpush
