
@extends('layouts.center')
@section('style')
@endsection
@section('content')
    <div class="container-fluid  pl-3 pl-lg-5 pr-3 pr-lg-5">
       <div class="row"> 

          <div class="col-lg-12">
                <div class="d-sm-flex align-items-center justify-content-between">
                    <div class="custom-heading-wrapper">
                        <h1 class="h1">Profiles</h1>
                        <span class="helpNoteLink" data-toggle="collapse" data-target="#notes" aria-expanded="true">
                            <b>Help?</b></span>
                    </div>
                    @if (request('from') == 'dashboard')
                        <div class="back-to-dashboard">
                            <a href="{{ url()->previous() ?? route('dashboard.home') }}">
                                <img src="{{ asset('assets/dashboard/img/crossimg.png') }}" alt="Back To Dashboard">
                            </a>
                        </div>
                    @endif
                </div>
            </div>
          <div class="col-md-12 mb-4">
             <div class="card collapse" id="notes">
                <div class="card-body">
                  <h3 class="NotesHeader"><b>Notes:</b></h3>
                   <ol>
                        <li>The following statistics are a summary of the activity generated by Users who have viewed your Profile pages.</li>
                        <li>View your statistics here for your Profile views</li>
                        <li>For Masseur statistics, go to <a href="{{ route('masseurs') }}" class="custom_links_design">Masseurs</a>.</li>
                   </ol>
                </div>
             </div>
          </div>
       </div>

     <div class="row">
        
     <div class="col-lg-12 card-wrapper">                
        <div class="row p-4 rounded" style="background-color: #c2cfe052;">                  
            <div class="col-lg-12">
                <h4 class="font-weight-bold" style="color: var(--blue--text);">Profile Statistics
                </h4>
            </div>
           <div class="col-lg-12 card-list-wrapper">
           
                <div class="statistics-card shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label">Profile Views Today
                        </div>
                        <div class="statistics-value">125</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/view-profile.png') }}" alt="icon">
                    </div>
                </div>
           
                <div class="statistics-card shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label">Profile Views This Week
                        </div>
                        <div class="statistics-value">35</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/view-profile-time.png') }}" alt="icon">
                    </div>
                </div>
           
                <div class="statistics-card shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label"> Year to Date
                        </div>
                        <div class="statistics-value">125</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/calendar.png') }}" alt="icon">
                    </div>
                </div>
           </div>
            <div class="col-lg-12 card-list-wrapper">    
                <div class="statistics-card shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label">Playbox Views Today
                        </div>
                        <div class="statistics-value">125</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/likes.png') }}" alt="icon">
                    </div>
                </div>
             
           
                <div class="statistics-card shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label">Playbox Views This Week
                        </div>
                        <div class="statistics-value">35</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/likes.png') }}" alt="icon">
                    </div>
                </div>
            
           
                <div class="statistics-card shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label"> Year to Date
                        </div>
                        <div class="statistics-value">125</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/calendar.png') }}" alt="icon">
                    </div>
                </div>
           </div>
        </div> 
    </div>
    {{-- end --}}
    {{-- fourth row --}}
    <div class="col-lg-12 card-wrapper">                
        <div class="row p-4 rounded my-2" style="background-color: #c2cfe052;">                  
            <div class="col-lg-12">
                <h4 class="font-weight-bold" style="color: var(--blue--text);">Media Statistics
                </h4>
            </div>
            <div class="col-lg-12 card-list-wrapper">
                <div class="statistics-card d-flex justify-content-between align-items-center shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label">Media Views Today
                        </div>
                        <div class="statistics-value">125</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/media-view.png') }}" alt="icon">
                    </div>
                </div>
        
                <div class="statistics-card d-flex justify-content-between align-items-center shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label">Media Views This Weeks
                        </div>
                        <div class="statistics-value">35</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/media-view.png') }}" alt="icon">
                    </div>
                </div>
                <div class="statistics-card d-flex justify-content-between align-items-center shadow-sm">
                    <div class="statistics-text">
                        <div class="statistics-label">Year to Date
                        </div>
                        <div class="statistics-value">125</div>
                    </div>
                    <div class="statistics-icon">
                        <img src="{{ asset('assets/dashboard/img/calendar.png') }}" alt="icon">
                    </div>
                </div>
            </div>
        </div>
    </div>
     </div>
    </div>
@endsection
@push('script')

@endpush
